name: CI

on:
  push:
    paths:
      - '**.zig'
      - 'gyro.zzz'
  pull_request:
     paths:
      - '**.zig'
      - 'gyro.zzz'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1
      
      - name: build
        run: gyro build -fstage1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check --ast-check **.zig
