name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - uses: mattnite/setup-gyro@v1.1.0
      
      - name: gyro
        run: gyro update
      
      - name: build
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: zig fmt --check --ast-check .
