name: Publish

on:
  push:
    paths:
      - 'gyro.zzz'
  workflow_dispatch:

jobs:
  test:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - uses: mattnite/setup-gyro@v1.1.0
      
      - name: build
        run: gyro build test
  publish:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: mattnite/setup-gyro@v1.1.0
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: gyro publish
        env:
          GYRO_ACCESS_TOKEN: ${{ secrets.GYRO_ACCESS_TOKEN }}
